name: Output Event Details on issues 
on:
  issues:
    types: [opened, edited, deleted]
jobs:
  OutputEventDetails:
    runs-on: ubuntu-latest
    steps: 
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}" 